# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bizaar < Formula
  desc "CLI for interacting with your Bizaar apps"
  homepage "https://github.com/civo/bizaar-cli"
  version "0.0.10"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/civo/bizaar-cli/releases/download/v0.0.10/bizaar-0.0.10-darwin-amd64.tar.gz"
    sha256 "35d692550a167abfe1d06591ca9c25ad44b69f032800f8b7a8964154b7a3905b"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/civo/bizaar-cli/releases/download/v0.0.10/bizaar-0.0.10-darwin-arm64.tar.gz"
    sha256 "450d9fe9453e70590f13d499b08baea2ddbbcdb8ad4dfcc1913568268ff97727"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/civo/bizaar-cli/releases/download/v0.0.10/bizaar-0.0.10-linux-amd64.tar.gz"
    sha256 "78ee7cd92c07ec88e8c186b9a10f9f8ece1a5ea10bc60fcd220119cd052edee2"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/civo/bizaar-cli/releases/download/v0.0.10/bizaar-0.0.10-linux-arm.tar.gz"
    sha256 "5bc2ff5979e82b587bb182e4c1d45125b7487fdcc8c3e626750e39ad27f98e18"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/civo/bizaar-cli/releases/download/v0.0.10/bizaar-0.0.10-linux-arm64.tar.gz"
    sha256 "fa10707407eab0a1258addfa63d8ad5ac6fbbdd21ddb8bb6642797b7675e0493"
  end

  def install
    bin.install "bizaar"
  end
end
