# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Bizaar < Formula
  desc "CLI for interacting with your Bizaar apps"
  homepage "https://github.com/civo/bizaar-cli"
  version "0.0.13"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/civo/bizaar-cli/releases/download/v0.0.13/bizaar-0.0.13-darwin-amd64.tar.gz"
    sha256 "d2d0e88a41938826994d55860f36e01b45eff3006d672db290d6d619e9457570"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/civo/bizaar-cli/releases/download/v0.0.13/bizaar-0.0.13-darwin-arm64.tar.gz"
    sha256 "0131cf2cab409855d8223abc4611c956be65efe1531dca3e2ed673de36ba146e"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/civo/bizaar-cli/releases/download/v0.0.13/bizaar-0.0.13-linux-amd64.tar.gz"
    sha256 "20592a945f037fd1991fc5b70df6f21993793f6f02f97af35d697a40997302cf"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/civo/bizaar-cli/releases/download/v0.0.13/bizaar-0.0.13-linux-arm.tar.gz"
    sha256 "863ec50a6127665d6fba56607043b9a4ccc6245545817395469dc2448a01d114"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/civo/bizaar-cli/releases/download/v0.0.13/bizaar-0.0.13-linux-arm64.tar.gz"
    sha256 "2b8851146b8e53eb722ecec9913501906210432d09aa6a91e0758c637d395b79"
  end

  def install
    bin.install "bizaar"
  end
end
