# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Civo < Formula
  desc "CLI for managing Civo resources."
  homepage "https://github.com/civo/cli"
  version "1.0.33"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/civo/cli/releases/download/v1.0.33/civo-1.0.33-darwin-amd64.tar.gz"
      sha256 "3f76d2593823449d60773153d3b051b8586051e57ee2f62ef720955975ca0181"

      def install
        bin.install "civo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/civo/cli/releases/download/v1.0.33/civo-1.0.33-darwin-arm64.tar.gz"
      sha256 "2706ea4edfb32859e5453521b6b265e555bc9747194b5298f2cb280bd4710f27"

      def install
        bin.install "civo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/civo/cli/releases/download/v1.0.33/civo-1.0.33-linux-amd64.tar.gz"
      sha256 "ac65a908cecae1aa7fa94b3caa57b64119c537825f6a7584a5bf3e4754fd5a91"

      def install
        bin.install "civo"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/civo/cli/releases/download/v1.0.33/civo-1.0.33-linux-arm.tar.gz"
      sha256 "b52a07beaf8b7c80bcf3a1ea81285a7abe3486c304c183b55f70d47f1baa1cc8"

      def install
        bin.install "civo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/civo/cli/releases/download/v1.0.33/civo-1.0.33-linux-arm64.tar.gz"
      sha256 "234feb98561d5905d1183b7623e00dd5217a731f0b1a1b2d2b9dbc07d63ae98c"

      def install
        bin.install "civo"
      end
    end
  end
end
