# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Civo < Formula
  desc "CLI for managing Civo resources."
  homepage "https://github.com/civo/cli"
  version "1.0.46"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/civo/cli/releases/download/v1.0.46/civo-1.0.46-darwin-amd64.tar.gz"
      sha256 "c7586f4f4e3e17e1ef4837c4fded9d2d56fd336b5c34af972855d26ffbdedf49"

      def install
        bin.install "civo"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/civo/cli/releases/download/v1.0.46/civo-1.0.46-darwin-arm64.tar.gz"
      sha256 "4cbc7aefd1500e70cccfe1922942fdf1864efeee0cb7258abeb9f57484486376"

      def install
        bin.install "civo"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/civo/cli/releases/download/v1.0.46/civo-1.0.46-linux-amd64.tar.gz"
      sha256 "5422e96c94fcbd8308af1bbb2c3ad69823e969f3eb650fbb5d5ab182f076d1c6"

      def install
        bin.install "civo"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/civo/cli/releases/download/v1.0.46/civo-1.0.46-linux-arm64.tar.gz"
      sha256 "e4a51d160df45fa0c242f4a7065278f1e62bc7493f5654c938535fd0747cf73d"

      def install
        bin.install "civo"
      end
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/civo/cli/releases/download/v1.0.46/civo-1.0.46-linux-arm.tar.gz"
      sha256 "21c94d9bf1473eff1afcdbca382b7959745b56e191e1a56778fb79bed326536c"

      def install
        bin.install "civo"
      end
    end
  end
end
