# This file was generated by GoReleaser. DO NOT EDIT.
class Civo < Formula
  desc "CLI for managing Civo resources."
  homepage "https://github.com/civo/cli"
  version "0.6.7"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/civo/cli/releases/download/v0.6.7/civo-0.6.7-darwin-amd64.tar.gz"
    sha256 "bdbb7d285e2715696600fac699e9faa95804cbded1bbacba8b957b055e669ddf"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/civo/cli/releases/download/v0.6.7/civo-0.6.7-linux-amd64.tar.gz"
      sha256 "7fb71042c288819e1f9670c13bbb8315eddece9ad4ee64ccbb7209cd53183d60"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
      else
        url "https://github.com/civo/cli/releases/download/v0.6.7/civo-0.6.7-linux-arm.tar.gz"
        sha256 "e2569a014917df2981d1bd38a4e73157d320d08c6e6959ecf114bb14ac21d269"
      end
    end
  end

  def install
    bin.install "civo"
  end
end
