# This file was generated by GoReleaser. DO NOT EDIT.
class Civo < Formula
  desc "CLI for managing Civo resources."
  homepage "https://github.com/civo/cli"
  version "0.6.1"
  bottle :unneeded

  if OS.mac?
    url "https://github.com/civo/cli/releases/download/v0.6.1/civo-0.6.1-darwin-amd64.tar.gz"
    sha256 "fb65c1c1a2d86f12420f85c9334d757be4a0e45482f2bd9d6abddb4069f64e9b"
  elsif OS.linux?
    if Hardware::CPU.intel?
      url "https://github.com/civo/cli/releases/download/v0.6.1/civo-0.6.1-linux-amd64.tar.gz"
      sha256 "1578371e1132acc789518e1481dc3529b0ab5a9594217b1d29bcc4e67515c8fb"
    end
    if Hardware::CPU.arm?
      if Hardware::CPU.is_64_bit?
      else
        url "https://github.com/civo/cli/releases/download/v0.6.1/civo-0.6.1-linux-arm.tar.gz"
        sha256 "a2aeb56fd1f400435a31c197873f50b3aff58110dc27b51504f087168a7c841c"
      end
    end
  end

  def install
    bin.install "civo"
  end
end
