# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubemart < Formula
  desc "CLI for interacting with your Kubemart apps"
  homepage "https://github.com/kubemart/kubemart-cli"
  version "0.0.16"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/kubemart/kubemart-cli/releases/download/v0.0.16/kubemart-0.0.16-darwin-amd64.tar.gz"
    sha256 "f34900cff6ad14dc74cd81530dd81177ffde72c88492c7445b10baf9be515e50"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/kubemart/kubemart-cli/releases/download/v0.0.16/kubemart-0.0.16-darwin-arm64.tar.gz"
    sha256 "e74be6adcea5855e2abe48b184853c68c29af72538074bfe3924a53973e18aca"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/kubemart/kubemart-cli/releases/download/v0.0.16/kubemart-0.0.16-linux-amd64.tar.gz"
    sha256 "d4b5241199ef4a3687bddd352ca0e8e458e4976972adff080fdac2cc4d68814f"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/kubemart/kubemart-cli/releases/download/v0.0.16/kubemart-0.0.16-linux-arm.tar.gz"
    sha256 "b69f1928152d8910285c440912f69c6417346339efdce4e0b9eb2e0c065ec381"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/kubemart/kubemart-cli/releases/download/v0.0.16/kubemart-0.0.16-linux-arm64.tar.gz"
    sha256 "940801bc41ddbc5cd074e5b017e4801598f9625661f0c408a37a07cb63283c1e"
  end

  def install
    bin.install "kubemart"
  end
end
