# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubemart < Formula
  desc "CLI for interacting with your Kubemart apps"
  homepage "https://github.com/kubemart/kubemart-cli"
  version "0.0.33"
  bottle :unneeded

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/kubemart/kubemart-cli/releases/download/v0.0.33/kubemart-0.0.33-darwin-amd64.tar.gz"
      sha256 "ed729cb1bcd8a366ac01115ebadc1faf32f5e059d7677f44ffbc193c15adee2b"
    end
    if Hardware::CPU.arm?
      url "https://github.com/kubemart/kubemart-cli/releases/download/v0.0.33/kubemart-0.0.33-darwin-arm64.tar.gz"
      sha256 "44cb62c87b978b4d49aafc859721ab3a998db9d1b0110f4d8460f72f74d52127"
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/kubemart/kubemart-cli/releases/download/v0.0.33/kubemart-0.0.33-linux-amd64.tar.gz"
      sha256 "3ae6ada700a5e56b82daf682d9f1038ada1f52a3d301e04b57aa1aa96a6a244e"
    end
    if Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
      url "https://github.com/kubemart/kubemart-cli/releases/download/v0.0.33/kubemart-0.0.33-linux-arm.tar.gz"
      sha256 "831c33fcf3cafda6e11c5b90f013cc5d24c59b182e337da751d3455baacd4f6d"
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/kubemart/kubemart-cli/releases/download/v0.0.33/kubemart-0.0.33-linux-arm64.tar.gz"
      sha256 "f1bad2a290ef9810248ea96ecd86db1229cad31379f72447714e0bf224d0815c"
    end
  end

  def install
    bin.install "kubemart"
  end
end
