# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Kubemart < Formula
  desc "CLI for interacting with your Kubemart apps"
  homepage "https://github.com/kubemart/kubemart-cli"
  version "0.0.21"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/kubemart/kubemart-cli/releases/download/v0.0.21/kubemart-0.0.21-darwin-amd64.tar.gz"
    sha256 "896516cfe9147c1927300aeb641d59e01aff6bb58f306b4dcd64034432d93145"
  end
  if OS.mac? && Hardware::CPU.arm?
    url "https://github.com/kubemart/kubemart-cli/releases/download/v0.0.21/kubemart-0.0.21-darwin-arm64.tar.gz"
    sha256 "927bb1a5fa860125ddbabf345a49e4e968fb420df23ce5587421fa9b9d858d49"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/kubemart/kubemart-cli/releases/download/v0.0.21/kubemart-0.0.21-linux-amd64.tar.gz"
    sha256 "6a508346dfbdd6da3dbd322ebfef90324326e56666152f2dd12ad5037eb1830a"
  end
  if OS.linux? && Hardware::CPU.arm? && !Hardware::CPU.is_64_bit?
    url "https://github.com/kubemart/kubemart-cli/releases/download/v0.0.21/kubemart-0.0.21-linux-arm.tar.gz"
    sha256 "139aee1ca0f3799c693e4c13359b1e401f9ab024041c863a32ab7b9d466084a6"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/kubemart/kubemart-cli/releases/download/v0.0.21/kubemart-0.0.21-linux-arm64.tar.gz"
    sha256 "51f37dfbd10f010f08f4aaedbb0d49245d448da673eb0d6b32d3bb4b9ef33a32"
  end

  def install
    bin.install "kubemart"
  end
end
